# OpenPoll GitLab CI/CD Configuration

# Define the stages for the pipeline
stages:
  - setup
  - lint
  - build
  - test
  - security

# Define default image and cache settings
default:
  image: node:20
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - functions/node_modules/

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - when: never

# Install dependencies
setup:
  stage: setup
  script:
    - cd functions
    - npm ci
  artifacts:
    paths:
      - functions/node_modules/
    expire_in: 1 hour
  allow_failure: false

# Lint check
lint:
  stage: lint
  script:
    - cd functions
    - npm run lint
  dependencies:
    - setup
  allow_failure: false

# Build the project
build:
  stage: build
  script:
    - cd functions
    - npm run build
  dependencies:
    - setup
  artifacts:
    paths:
      - functions/lib/
    expire_in: 1 hour
  allow_failure: false

# Include security scanning templates
include:
  - template: Security/SAST.gitlab-ci.yml

# Configure SAST
sast:
  stage: security
  allow_failure: false
