name: OpenPoll CI/CD

on:
  push:
    branches: [upgrade-to-nodev22]
    tags: ['v*']


env:
  NODE_VERSION: 22

jobs:
  deploy_test:
    name: Deploy for Testing
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 -d > $HOME/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json" >> $GITHUB_ENV

      - name: Configure Firebase Project
        run: |
          # Set the Firebase project using the secret
          firebase use ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Verify Firebase Configuration
        run: |
          firebase projects:list
          firebase use --current

      - name: Set .env values
        working-directory: functions
        run: |
          echo "SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN_PROD }}" >> .env
          echo "SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET_PROD }}" >> .env
          echo "DEFAULT_FUNCTIONS_LOCATION=${{ secrets.DEFAULT_FUNCTIONS_LOCATION }}" >> .env

      - name: Install Dependencies
        working-directory: functions
        run: npm ci

      - name: Build Functions
        working-directory: functions
        run: npm run build

      - name: Deploy to Firebase
        run: |
          firebase deploy --only functions --project ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-key.json
